### ISSUE TITLE
ICalendarAgenda Revisor/iTIPProccess bug

### ISSUE THREAD

**Issue by ConorMurphy21** [JFXtras/jfxtras#98]
I have made changes to my java in ICalendarAgenda but I haven't really touched the revisers or iTIP methods at all, I also think I saw this bug before I edited but couldn't recreate it at the time. 

Bug:
If a reccuring weekly event is edited, and the option "this event only" is selected. The calendar will be unable to delete this event. I followed the trail and it seems that the deleter code is fine and gives the right results, but The iTIP proccessing logs a successful delete but does not alter the vcalendar.

As well I wanted to find out if it was a bug that daily, monthly, and yearly recurrences do not give the option to edit "this event only" or if that was a design choice and why.

**Comment by daviddbal** [comment]
I'll take a look at this issue soon.  I'm swamped with other work right now, but I should get a chance in the next few days.  Thanks for bringing this to my attention.

**Comment by ConorMurphy21** [comment]
Ok thanks,
Just to let you know the graphics issue has been fixed (and was my fault) .
But I made a new project from the github jar and the deleting of editted
recurrences is still a problem. As well as the inability to edit single
events that reccure daily or monthly.

Cheers,
Conor

**Comment by daviddbal** [comment]
The best thing to help me fix a bug is ready-to-run example code that demonstrates the behavior.  Could you prepare the example code?  If the problem is only graphical, then please give me simple instructions on how to replicate it.

**Comment by ConorMurphy21** [comment]
The example is not graphic but I can give you instructions on how to
recreate:

Bug #1:
1. Create event in icalendaragenda with a weekly reccurence
2. Edit a reccurence of the created event (descriptive or time) and select
"this event only" when prompted.
3. Select the editted reccurence and press delete (nothing should happen,
no prompt for options either, log says successful delete)

Bug #2:
Not sure if this is a bug or a feature but the option to edit "this event
only" on an instance of an event reccuring daily, monthly or yearly is not
given.
1. Create event that reccures daily
2. Select a reccurence/edit a reccurence
3. Prompt will only show "all events,", and,"this and future".

And I will send a test case of proccessCancel (that seems to be the
location of the problem) of the first bug when I get the chance.
Hope this help,
Sorry about poor communication I'm in highschool so I haven't really
learned the technical edicate side of the industry.
Cheers,
Conor

**Comment by daviddbal** [comment]
Connor,
I'm finally working on these issues.  I've confirmed the bugs existence - they are both bugs.  I'll fix them.  I'll also make some test cases to ensure no regressions pop up in the future.  If you know of any other problems please tell me now.  It will be easier for me to fix all problems at once.
-David Bal 
    On Thursday, April 12, 2018, 1:42:08 PM MDT, ConorMurphy21 <notifications@github.com> wrote:  
 
 The example is not graphic but I can give you instructions on how to
recreate:

Bug #1:
1. Create event in icalendaragenda with a weekly reccurence
2. Edit a reccurence of the created event (descriptive or time) and select
"this event only" when prompted.
3. Select the editted reccurence and press delete (nothing should happen,
no prompt for options either, log says successful delete)

Bug #2:
Not sure if this is a bug or a feature but the option to edit "this event
only" on an instance of an event reccuring daily, monthly or yearly is not
given.
1. Create event that reccures daily
2. Select a reccurence/edit a reccurence
3. Prompt will only show "all events,", and,"this and future".

And I will send a test case of proccessCancel (that seems to be the
location of the problem) of the first bug when I get the chance.
Hope this help,
Sorry about poor communication I'm in highschool so I haven't really
learned the technical edicate side of the industry.
Cheers,
Conor

**Comment by daviddbal** [comment]
Bug #1 was real easy.  I had a refresh() in the wrong place in ICalendarAgenda (around line 390) and it only affected deletes and not edits.
Bug #2 is due to equals failing for RRULE.  Editing one recurrence is not suppose to be an option when the RRULE was changed so when equals was returning false (the real bug) the edit one option was left out.
-David Bal
P.S.  I only changed branch 8.0.  Which branch are you using?


    On Thursday, April 12, 2018, 1:42:08 PM MDT, ConorMurphy21 <notifications@github.com> wrote:  
 
 The example is not graphic but I can give you instructions on how to
recreate:

Bug #1:
1. Create event in icalendaragenda with a weekly reccurence
2. Edit a reccurence of the created event (descriptive or time) and select
"this event only" when prompted.
3. Select the editted reccurence and press delete (nothing should happen,
no prompt for options either, log says successful delete)

Bug #2:
Not sure if this is a bug or a feature but the option to edit "this event
only" on an instance of an event reccuring daily, monthly or yearly is not
given.
1. Create event that reccures daily
2. Select a reccurence/edit a reccurence
3. Prompt will only show "all events,", and,"this and future".

And I will send a test case of proccessCancel (that seems to be the
location of the problem) of the first bug when I get the chance.
Hope this help,
Sorry about poor communication I'm in highschool so I haven't really
learned the technical edicate side of the industry.
Cheers,
Conor

**Comment by daviddbal** [comment]
Bug #2 is not a failure of equals.  It is a result of the copy of ByRules being an empty list instead of null, which is causing equals to fail.  I'm tired and I'll fix it later.  I'll get it soon.-David
    On Thursday, April 12, 2018, 1:42:08 PM MDT, ConorMurphy21 <notifications@github.com> wrote:  
 
 The example is not graphic but I can give you instructions on how to
recreate:

Bug #1:
1. Create event in icalendaragenda with a weekly reccurence
2. Edit a reccurence of the created event (descriptive or time) and select
"this event only" when prompted.
3. Select the editted reccurence and press delete (nothing should happen,
no prompt for options either, log says successful delete)

Bug #2:
Not sure if this is a bug or a feature but the option to edit "this event
only" on an instance of an event reccuring daily, monthly or yearly is not
given.
1. Create event that reccures daily
2. Select a reccurence/edit a reccurence
3. Prompt will only show "all events,", and,"this and future".

And I will send a test case of proccessCancel (that seems to be the
location of the problem) of the first bug when I get the chance.
Hope this help,
Sorry about poor communication I'm in highschool so I haven't really
learned the technical edicate side of the industry.
Cheers,
Conor

**Comment by daviddbal** [comment]
I fixed bug #2 too.  The fixes are only in branch 8.0.  I'll migrate to other branches later.
    On Thursday, April 12, 2018, 1:42:08 PM MDT, ConorMurphy21 <notifications@github.com> wrote:  
 
 The example is not graphic but I can give you instructions on how to
recreate:

Bug #1:
1. Create event in icalendaragenda with a weekly reccurence
2. Edit a reccurence of the created event (descriptive or time) and select
"this event only" when prompted.
3. Select the editted reccurence and press delete (nothing should happen,
no prompt for options either, log says successful delete)

Bug #2:
Not sure if this is a bug or a feature but the option to edit "this event
only" on an instance of an event reccuring daily, monthly or yearly is not
given.
1. Create event that reccures daily
2. Select a reccurence/edit a reccurence
3. Prompt will only show "all events,", and,"this and future".

And I will send a test case of proccessCancel (that seems to be the
location of the problem) of the first bug when I get the chance.
Hope this help,
Sorry about poor communication I'm in highschool so I haven't really
learned the technical edicate side of the industry.
Cheers,
Conor

**Comment by ConorMurphy21** [comment]
Thank you so much for taking a look at these bugs. I have not found any
others from my time testing my project but I am sending it out to a couple
other people for testing and will let you know if they find any. I
unfortunately have no experience with github and don't know what branches
are. In my project I used the main jfxtras as dependancies but since
calendarfx and icalendaragenda weren't in maven I just downloaded a zip
from github and included them in my project. I know this is a little
tedious and annoying but if possible could you just let me know what files
I should redownload, and if the bugs were fixed in iCalendarAgenda.java
where they are (I have made some modifications to this file). Lastly, when
you said about bug #2 that when the recurrence has been edited it is not an
option to edit a single vevent. Could you explain a little more what this
situation encompasses. I have a system in place on my project that
automatically edits employees out of shifts if the employee has requested
that time off.This system always uses "this event only" and I'm just
wondering when I have to use "this and future events" and why? Anyways
thanks for all the help!

**Comment by tbee** [comment]
The calendarFX artifacts are on Maven, so I suggest you start using those.
http://central.maven.org/maven2/org/jfxtras/jfxtras-icalendaragenda/
https://oss.sonatype.org/content/repositories/snapshots/org/jfxtras/jfxtras-icalendarfx/

The branch is equal to the version; so what version are you using (since you probably downloaded the default branch at the time, it most likely is the 8). What Java version are you using?

**Comment by ConorMurphy21** [comment]
I'm using java 8, and thanks didn't notice I'll start using the icalendarfx
maven repository. I followed all the steps from the commit, and daily is
now showing "this event only", but I have platform.runlater that uses the
agenda's recurrence rule and it now throughs an error about the dates being
null. As well I moved the refresh for bug #1 but the appointment (and
vevent) are still not deleted. I need to go to bed now but I will try
running the original calendar tomorrow and find out if I just did something
wrong.

On Apr 20, 2018 1:59 AM, "Tom Eugelink" <notifications@github.com> wrote:

The calendarFX artifacts are on Maven, so I suggest you start using those.
http://central.maven.org/maven2/org/jfxtras/jfxtras-icalendaragenda/
https://oss.sonatype.org/content/repositories/snapshots/org/jfxtras/jfxtras-icalendarfx/

The branch is equal to the version; so what version are you using (since
you probably downloaded the default branch at the time, it most likely is
the 8). What Java version are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JFXtras/jfxtras/issues/98#issuecomment-382987448>, or mute
the thread

**Comment by tbee** [comment]
In that case use the 8.0-r7-SNAPSHOT so changes David makes are automatically published in the nightly build.

**Comment by daviddbal** [comment]
The only changed files that are important are in iCalendarAgenda.  I did change some files in iCalendarFx, but they were just added tests.  Right now the changes are only on branch 8.0.  If you want to see which files were changed please review my 2 commits.  You could download a zip of that branch now.  Later today or tonight I'll migrate the changes to the other branches (9.0 and 10.0).
Bug #2 is gone.  The option to select one recurrence is there now.  The reason the bug was there a bit complicated.  The correct behavior is the following; when you edit a RRULE property (e.g. FREQUENCY) you shouldn't be able to change just one recurrence, but if you edit any non-RRULE field (e.g. SUMMARY) the edit-one option should be there.  The behavior is correct now.
Just a suggestion, you should try to learn a build tool to get your dependencies automatically (e.g. Maven or Gradle).  They effort is worth it.
-David Bal
    On Thursday, April 19, 2018, 11:43:29 PM MDT, ConorMurphy21 <notifications@github.com> wrote:  
 
 Thank you so much for taking a look at these bugs. I have not found any
others from my time testing my project but I am sending it out to a couple
other people for testing and will let you know if they find any. I
unfortunately have no experience with github and don't know what branches
are. In my project I used the main jfxtras as dependancies but since
calendarfx and icalendaragenda weren't in maven I just downloaded a zip
from github and included them in my project. I know this is a little
tedious and annoying but if possible could you just let me know what files
I should redownload, and if the bugs were fixed in iCalendarAgenda.java
where they are (I have made some modifications to this file). Lastly, when
you said about bug #2 that when the recurrence has been edited it is not an
option to edit a single vevent. Could you explain a little more what this
situation encompasses. I have a system in place on my project that
automatically edits employees out of shifts if the employee has requested
that time off.This system always uses "this event only" and I'm just
wondering when I have to use "this and future events" and why? Anyways
thanks for all the help!

**Comment by ConorMurphy21** [comment]
Ok, I have followed all of the steps on your commits, and I also have set
up a test project with a basic icalendaragenda and maven branch 8 of
icalendarfx and a downloaded icalendaragenda. (I tried the maven repo but
it still had bug #2 so I assumed it hadn't been updated. Bug #2 seems to be
fixed and thanks for clarifying when edit one can't be used. Unfortunately
I still find bug #1 in both my test project and my personal project. If you
don't I can give you more information about my test setup to see what the
difference is. Lastly, my project uses maven and I think it is a great
tool, but iCalendarAgenda and icalendarFx were not maven repositories a few
months ago when I downloaded it and since then I added features to it.

**Comment by tbee** [comment]
icalendarfx has been in de 8.0-r6-snapshot for many months in Maven. But are your added features interesting enough to be contributed back?

**Comment by ConorMurphy21** [comment]
Hmm, thats wierd. I remember looking for a very long time and searching
jfxtras in the repository. Unfortunately the features I was talking about
are not really features useful to the majority of people using
icalendaragenda. I used it as a framework to create shifts to be filled for
a schedule so I made some alterations to what could be set when editting
events. I set up a choicebox for choosing employees (but only employees
availible during that time). Also removing employees from shifts
automatically if they have requested that time off. Sorry to disappoint or
mislead.

**Comment by tbee** [comment]
Snapshots are not in Maven central (of course), but in Sonatype's snapshot repository. Maven central only holds releases.

**Comment by tbee** [comment]
What you made are assigning available resources, not necessarily a bad extension...

**Comment by ConorMurphy21** [comment]
Well, I am an amateur, and what I did in my personal project wasn't done
very elegantly. But I would be happy to work on extension would make the
edit popups more customizable and could store extravariables in x vars in
the ics file. If that's something you would be interested in adding, I
would be happy to contribute to this project.

**Comment by tbee** [comment]
Well, it's David's brainchild, so he has the last say in it of course, but personally any good contribution is welcome. We do require things like regression tests for JFXtras code. Is it possible to create a kind of add-on within the JFXtras-labs project first?

**Comment by ConorMurphy21** [comment]
Well, I could make the customizable popups inside labs, but the vcomponents
would need to updated to support parsing custom attributes. If your
interested in this idea I would be happy to write an execution plan or
something.

On Apr 21, 2018 5:03 PM, "Tom Eugelink" <notifications@github.com> wrote:

Well, it's David's brainchild, so he has the last say in it of course, but
personally any good contribution is welcome. We do require things like
regression tests for JFXtras code. Is it possible to create a kind of
add-on within the JFXtras-labs project first?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JFXtras/jfxtras/issues/98#issuecomment-383330576>, or mute
the thread

**Comment by ConorMurphy21** [comment]
Hey, was wondering if you've had a chance to look at the first bug. I still
find the edited recurrences are not given a delete popup. When checking
logs it says its a successful delete. I don't believe this is just a
refresh issue because when I save and reload the calendar it loads the
event I was trying to delete.

Also, I found 2 more bugs:
Bug #3:
ICalendarAgenda's setDisplayedLocalDateTime will not scroll to the time if
set when initializing. It will work with Platform. Runlater but it looks
buggy because it will show the shifts at 0 first then scroll.

Bug #4:
This is caused by me but I believe its a feature that would make
icalendaragenda a little better. When the agenda is in fullscreen mode, the
popups make the main stage disapear. I found that setting iniowner would
fix this but it caused a new problem. When I set iniowner on the
editAppointmentPopup it no longer allows me to save.

To replicate:
Bug #3:
In basic agenda calling class add this line:
agenda.setDisplayedLocalDateTime(LocalDateTime.of(LocalDate.now().plusWeeks(1),LocalTime.of(20,0))));

Bug #4:
At around line 543 of iCalendaragenda, before popupStage.show() in the
creation of editAppointmentCallback, add the line
popupStage.iniOwner(this.getScene().getWindow());

Sorry if bug #4 is just my stupidity. Thanks for any help

On Apr 12, 2018 3:06 PM, "David Bal" <notifications@github.com> wrote:

I'll take a look at this issue soon. I'm swamped with other work right now,
but I should get a chance in the next few days. Thanks for bringing this to
my attention.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JFXtras/jfxtras/issues/98#issuecomment-380912465>, or mute
the thread

**Comment by ConorMurphy21** [comment]
Ok just did a little more testing bug #4 takes a little more to replicate.

To recreate:
-Add line like original message in icalendar.
-make calendar fullscreen
-create an event that is repeatable
-advanced edit a recurring event
-either try to delete event from advanced edit or try to alter a trait ie
summary and then save. Both will not allow you to close the editAppointment
window.

On May 3, 2018 12:42 AM, "Conor Murphy" <imuniquest@gmail.com> wrote:

Hey, was wondering if you've had a chance to look at the first bug. I still
find the edited recurrences are not given a delete popup. When checking
logs it says its a successful delete. I don't believe this is just a
refresh issue because when I save and reload the calendar it loads the
event I was trying to delete.

Also, I found 2 more bugs:
Bug #3:
ICalendarAgenda's setDisplayedLocalDateTime will not scroll to the time if
set when initializing. It will work with Platform. Runlater but it looks
buggy because it will show the shifts at 0 first then scroll.

Bug #4:
This is caused by me but I believe its a feature that would make
icalendaragenda a little better. When the agenda is in fullscreen mode, the
popups make the main stage disapear. I found that setting iniowner would
fix this but it caused a new problem. When I set iniowner on the
editAppointmentPopup it no longer allows me to save.

To replicate:
Bug #3:
In basic agenda calling class add this line:
agenda.setDisplayedLocalDateTime(LocalDateTime.of(LocalDate.now().plusWeeks(1),LocalTime.of(20,0))));

Bug #4:
At around line 543 of iCalendaragenda, before popupStage.show() in the
creation of editAppointmentCallback, add the line
popupStage.iniOwner(this.getScene().getWindow());

Sorry if bug #4 is just my stupidity. Thanks for any help

On Apr 12, 2018 3:06 PM, "David Bal" <notifications@github.com> wrote:

I'll take a look at this issue soon. I'm swamped with other work right now,
but I should get a chance in the next few days. Thanks for bringing this to
my attention.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JFXtras/jfxtras/issues/98#issuecomment-380912465>, or mute
the thread

**Comment by daviddbal** [comment]
Thanks for bringing this to my attention.  I'll take a look as soon as I can.-David Bal
    On Wednesday, May 2, 2018, 10:58:08 PM MDT, ConorMurphy21 <notifications@github.com> wrote:  
 
 Ok just did a little more testing bug #4 takes a little more to replicate.

To recreate:
-Add line like original message in icalendar.
-make calendar fullscreen
-create an event that is repeatable
-advanced edit a recurring event
-either try to delete event from advanced edit or try to alter a trait ie
summary and then save. Both will not allow you to close the editAppointment
window.

On May 3, 2018 12:42 AM, "Conor Murphy" <imuniquest@gmail.com> wrote:

Hey, was wondering if you've had a chance to look at the first bug. I still
find the edited recurrences are not given a delete popup. When checking
logs it says its a successful delete. I don't believe this is just a
refresh issue because when I save and reload the calendar it loads the
event I was trying to delete.

Also, I found 2 more bugs:
Bug #3:
ICalendarAgenda's setDisplayedLocalDateTime will not scroll to the time if
set when initializing. It will work with Platform. Runlater but it looks
buggy because it will show the shifts at 0 first then scroll.

Bug #4:
This is caused by me but I believe its a feature that would make
icalendaragenda a little better. When the agenda is in fullscreen mode, the
popups make the main stage disapear. I found that setting iniowner would
fix this but it caused a new problem. When I set iniowner on the
editAppointmentPopup it no longer allows me to save.

To replicate:
Bug #3:
In basic agenda calling class add this line:
agenda.setDisplayedLocalDateTime(LocalDateTime.of(LocalDate.now().plusWeeks(1),LocalTime.of(20,0))));

Bug #4:
At around line 543 of iCalendaragenda, before popupStage.show() in the
creation of editAppointmentCallback, add the line
popupStage.iniOwner(this.getScene().getWindow());

Sorry if bug #4 is just my stupidity. Thanks for any help

On Apr 12, 2018 3:06 PM, "David Bal" <notifications@github.com> wrote:

I'll take a look at this issue soon. I'm swamped with other work right now,
but I should get a chance in the next few days. Thanks for bringing this to
my attention.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JFXtras/jfxtras/issues/98#issuecomment-380912465>, or mute
the thread
